/*
 * This file is generated by jOOQ.
 */
package org.oana.storage.tables.pojos;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.oana.storage.tables.interfaces.IUserAdvancements;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "user_advancements",
    schema = "public"
)
public class UserAdvancements implements IUserAdvancements {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private OffsetDateTime createdAt;
    private OffsetDateTime startedAt;
    private UUID exerciseId;
    private OffsetDateTime completedAt;
    private Long sequenceNumber;

    public UserAdvancements() {}

    public UserAdvancements(IUserAdvancements value) {
        this.id = value.getId();
        this.createdAt = value.getCreatedAt();
        this.startedAt = value.getStartedAt();
        this.exerciseId = value.getExerciseId();
        this.completedAt = value.getCompletedAt();
        this.sequenceNumber = value.getSequenceNumber();
    }

    public UserAdvancements(
        UUID id,
        OffsetDateTime createdAt,
        OffsetDateTime startedAt,
        UUID exerciseId,
        OffsetDateTime completedAt,
        Long sequenceNumber
    ) {
        this.id = id;
        this.createdAt = createdAt;
        this.startedAt = startedAt;
        this.exerciseId = exerciseId;
        this.completedAt = completedAt;
        this.sequenceNumber = sequenceNumber;
    }

    /**
     * Getter for <code>public.user_advancements.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false)
    @NotNull
    @Override
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.user_advancements.id</code>.
     */
    @Override
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.user_advancements.created_at</code>.
     */
    @Column(name = "created_at", nullable = false, precision = 6)
    @Override
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.user_advancements.created_at</code>.
     */
    @Override
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.user_advancements.started_at</code>.
     */
    @Column(name = "started_at", precision = 6)
    @Override
    public OffsetDateTime getStartedAt() {
        return this.startedAt;
    }

    /**
     * Setter for <code>public.user_advancements.started_at</code>.
     */
    @Override
    public void setStartedAt(OffsetDateTime startedAt) {
        this.startedAt = startedAt;
    }

    /**
     * Getter for <code>public.user_advancements.exercise_id</code>.
     */
    @Column(name = "exercise_id", nullable = false)
    @NotNull
    @Override
    public UUID getExerciseId() {
        return this.exerciseId;
    }

    /**
     * Setter for <code>public.user_advancements.exercise_id</code>.
     */
    @Override
    public void setExerciseId(UUID exerciseId) {
        this.exerciseId = exerciseId;
    }

    /**
     * Getter for <code>public.user_advancements.completed_at</code>.
     */
    @Column(name = "completed_at", precision = 6)
    @Override
    public OffsetDateTime getCompletedAt() {
        return this.completedAt;
    }

    /**
     * Setter for <code>public.user_advancements.completed_at</code>.
     */
    @Override
    public void setCompletedAt(OffsetDateTime completedAt) {
        this.completedAt = completedAt;
    }

    /**
     * Getter for <code>public.user_advancements.sequence_number</code>.
     */
    @Column(name = "sequence_number", nullable = false)
    @Override
    public Long getSequenceNumber() {
        return this.sequenceNumber;
    }

    /**
     * Setter for <code>public.user_advancements.sequence_number</code>.
     */
    @Override
    public void setSequenceNumber(Long sequenceNumber) {
        this.sequenceNumber = sequenceNumber;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserAdvancements other = (UserAdvancements) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.startedAt == null) {
            if (other.startedAt != null)
                return false;
        }
        else if (!this.startedAt.equals(other.startedAt))
            return false;
        if (this.exerciseId == null) {
            if (other.exerciseId != null)
                return false;
        }
        else if (!this.exerciseId.equals(other.exerciseId))
            return false;
        if (this.completedAt == null) {
            if (other.completedAt != null)
                return false;
        }
        else if (!this.completedAt.equals(other.completedAt))
            return false;
        if (this.sequenceNumber == null) {
            if (other.sequenceNumber != null)
                return false;
        }
        else if (!this.sequenceNumber.equals(other.sequenceNumber))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.startedAt == null) ? 0 : this.startedAt.hashCode());
        result = prime * result + ((this.exerciseId == null) ? 0 : this.exerciseId.hashCode());
        result = prime * result + ((this.completedAt == null) ? 0 : this.completedAt.hashCode());
        result = prime * result + ((this.sequenceNumber == null) ? 0 : this.sequenceNumber.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserAdvancements (");

        sb.append(id);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(startedAt);
        sb.append(", ").append(exerciseId);
        sb.append(", ").append(completedAt);
        sb.append(", ").append(sequenceNumber);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUserAdvancements from) {
        setId(from.getId());
        setCreatedAt(from.getCreatedAt());
        setStartedAt(from.getStartedAt());
        setExerciseId(from.getExerciseId());
        setCompletedAt(from.getCompletedAt());
        setSequenceNumber(from.getSequenceNumber());
    }

    @Override
    public <E extends IUserAdvancements> E into(E into) {
        into.from(this);
        return into;
    }
}
