/*
 * This file is generated by jOOQ.
 */
package org.oana.storage.tables.daos;


import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.oana.storage.tables.Tags;
import org.oana.storage.tables.records.TagsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TagsDao extends DAOImpl<TagsRecord, org.oana.storage.tables.pojos.Tags, Long> {

    /**
     * Create a new TagsDao without any configuration
     */
    public TagsDao() {
        super(Tags.TAGS, org.oana.storage.tables.pojos.Tags.class);
    }

    /**
     * Create a new TagsDao with an attached configuration
     */
    public TagsDao(Configuration configuration) {
        super(Tags.TAGS, org.oana.storage.tables.pojos.Tags.class, configuration);
    }

    @Override
    public Long getId(org.oana.storage.tables.pojos.Tags object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.oana.storage.tables.pojos.Tags> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Tags.TAGS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.oana.storage.tables.pojos.Tags> fetchById(Long... values) {
        return fetch(Tags.TAGS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.oana.storage.tables.pojos.Tags fetchOneById(Long value) {
        return fetchOne(Tags.TAGS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<org.oana.storage.tables.pojos.Tags> fetchOptionalById(Long value) {
        return fetchOptional(Tags.TAGS.ID, value);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.oana.storage.tables.pojos.Tags> fetchRangeOfCreatedAt(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(Tags.TAGS.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<org.oana.storage.tables.pojos.Tags> fetchByCreatedAt(OffsetDateTime... values) {
        return fetch(Tags.TAGS.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.oana.storage.tables.pojos.Tags> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Tags.TAGS.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<org.oana.storage.tables.pojos.Tags> fetchByName(String... values) {
        return fetch(Tags.TAGS.NAME, values);
    }
}
