/*
 * This file is generated by jOOQ.
 */
package org.oana.storage.tables.interfaces;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "exercise_difficulties",
    schema = "public"
)
public interface IExerciseDifficulties extends Serializable {

    /**
     * Setter for <code>public.exercise_difficulties.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>public.exercise_difficulties.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    public Long getId();

    /**
     * Setter for <code>public.exercise_difficulties.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value);

    /**
     * Getter for <code>public.exercise_difficulties.created_at</code>.
     */
    @Column(name = "created_at", nullable = false, precision = 6)
    public OffsetDateTime getCreatedAt();

    /**
     * Setter for <code>public.exercise_difficulties.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>public.exercise_difficulties.name</code>.
     */
    @Column(name = "name")
    public String getName();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IExerciseDifficulties
     */
    public void from(IExerciseDifficulties from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IExerciseDifficulties
     */
    public <E extends IExerciseDifficulties> E into(E into);
}
