/*
 * This file is generated by jOOQ.
 */
package org.oana.storage.tables.interfaces;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "exercise_tags",
    schema = "public"
)
public interface IExerciseTags extends Serializable {

    /**
     * Setter for <code>public.exercise_tags.exercise_id</code>.
     */
    public void setExerciseId(UUID value);

    /**
     * Getter for <code>public.exercise_tags.exercise_id</code>.
     */
    @Id
    @Column(name = "exercise_id", nullable = false)
    @NotNull
    public UUID getExerciseId();

    /**
     * Setter for <code>public.exercise_tags.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value);

    /**
     * Getter for <code>public.exercise_tags.created_at</code>.
     */
    @Column(name = "created_at", nullable = false, precision = 6)
    public OffsetDateTime getCreatedAt();

    /**
     * Setter for <code>public.exercise_tags.tag_id</code>.
     */
    public void setTagId(Long value);

    /**
     * Getter for <code>public.exercise_tags.tag_id</code>.
     */
    @Column(name = "tag_id", nullable = false)
    @NotNull
    public Long getTagId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IExerciseTags
     */
    public void from(IExerciseTags from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IExerciseTags
     */
    public <E extends IExerciseTags> E into(E into);
}
