/*
 * This file is generated by jOOQ.
 */
package org.oana.storage.tables.interfaces;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;

import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "tags",
    schema = "public"
)
public interface ITags extends Serializable {

    /**
     * Setter for <code>public.tags.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>public.tags.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    public Long getId();

    /**
     * Setter for <code>public.tags.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value);

    /**
     * Getter for <code>public.tags.created_at</code>.
     */
    @Column(name = "created_at", nullable = false, precision = 6)
    public OffsetDateTime getCreatedAt();

    /**
     * Setter for <code>public.tags.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>public.tags.name</code>.
     */
    @Column(name = "name", nullable = false)
    @NotNull
    public String getName();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface ITags
     */
    public void from(ITags from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface ITags
     */
    public <E extends ITags> E into(E into);
}
