/*
 * This file is generated by jOOQ.
 */
package org.oana.storage.tables.interfaces;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotNull;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "user_type",
    schema = "public",
    uniqueConstraints = {
        @UniqueConstraint(name = "user_type_user_type_key", columnNames = { "user_type" })
    }
)
public interface IUserType extends Serializable {

    /**
     * Setter for <code>public.user_type.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>public.user_type.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    public Long getId();

    /**
     * Setter for <code>public.user_type.user_type</code>.
     */
    public void setUserType(String value);

    /**
     * Getter for <code>public.user_type.user_type</code>.
     */
    @Column(name = "user_type", nullable = false)
    @NotNull
    public String getUserType();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IUserType
     */
    public void from(IUserType from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IUserType
     */
    public <E extends IUserType> E into(E into);
}
