/*
 * This file is generated by jOOQ.
 */
package org.oana.storage.tables.interfaces;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "user_acounts",
    schema = "public"
)
public interface IUserAcounts extends Serializable {

    /**
     * Setter for <code>public.user_acounts.id</code>.
     */
    public void setId(UUID value);

    /**
     * Getter for <code>public.user_acounts.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false)
    public UUID getId();

    /**
     * Setter for <code>public.user_acounts.provider_id</code>.
     */
    public void setProviderId(UUID value);

    /**
     * Getter for <code>public.user_acounts.provider_id</code>.
     */
    @Column(name = "provider_id", nullable = false)
    @NotNull
    public UUID getProviderId();

    /**
     * Setter for <code>public.user_acounts.created_ad</code>.
     */
    public void setCreatedAd(LocalDateTime value);

    /**
     * Getter for <code>public.user_acounts.created_ad</code>.
     */
    @Column(name = "created_ad", precision = 6)
    public LocalDateTime getCreatedAd();

    /**
     * Setter for <code>public.user_acounts.user_type_id</code>.
     */
    public void setUserTypeId(Long value);

    /**
     * Getter for <code>public.user_acounts.user_type_id</code>.
     */
    @Column(name = "user_type_id")
    public Long getUserTypeId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IUserAcounts
     */
    public void from(IUserAcounts from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IUserAcounts
     */
    public <E extends IUserAcounts> E into(E into);
}
