/*
 * This file is generated by jOOQ.
 */
package org.oana.storage.tables.interfaces;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "user_advancements",
    schema = "public"
)
public interface IUserAdvancements extends Serializable {

    /**
     * Setter for <code>public.user_advancements.id</code>.
     */
    public void setId(UUID value);

    /**
     * Getter for <code>public.user_advancements.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false)
    @NotNull
    public UUID getId();

    /**
     * Setter for <code>public.user_advancements.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value);

    /**
     * Getter for <code>public.user_advancements.created_at</code>.
     */
    @Column(name = "created_at", nullable = false, precision = 6)
    public OffsetDateTime getCreatedAt();

    /**
     * Setter for <code>public.user_advancements.started_at</code>.
     */
    public void setStartedAt(OffsetDateTime value);

    /**
     * Getter for <code>public.user_advancements.started_at</code>.
     */
    @Column(name = "started_at", precision = 6)
    public OffsetDateTime getStartedAt();

    /**
     * Setter for <code>public.user_advancements.exercise_id</code>.
     */
    public void setExerciseId(UUID value);

    /**
     * Getter for <code>public.user_advancements.exercise_id</code>.
     */
    @Column(name = "exercise_id", nullable = false)
    @NotNull
    public UUID getExerciseId();

    /**
     * Setter for <code>public.user_advancements.completed_at</code>.
     */
    public void setCompletedAt(OffsetDateTime value);

    /**
     * Getter for <code>public.user_advancements.completed_at</code>.
     */
    @Column(name = "completed_at", precision = 6)
    public OffsetDateTime getCompletedAt();

    /**
     * Setter for <code>public.user_advancements.sequence_number</code>.
     */
    public void setSequenceNumber(Long value);

    /**
     * Getter for <code>public.user_advancements.sequence_number</code>.
     */
    @Column(name = "sequence_number", nullable = false)
    public Long getSequenceNumber();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IUserAdvancements
     */
    public void from(IUserAdvancements from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IUserAdvancements
     */
    public <E extends IUserAdvancements> E into(E into);
}
