/*
 * This file is generated by jOOQ.
 */
package org.oana.storage;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.oana.storage.tables.ExerciseDifficulties;
import org.oana.storage.tables.ExerciseTags;
import org.oana.storage.tables.Exercises;
import org.oana.storage.tables.Tags;
import org.oana.storage.tables.UserAcounts;
import org.oana.storage.tables.UserAdvancements;
import org.oana.storage.tables.UserType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.exercise_difficulties</code>.
     */
    public final ExerciseDifficulties EXERCISE_DIFFICULTIES = ExerciseDifficulties.EXERCISE_DIFFICULTIES;

    /**
     * The table <code>public.exercise_tags</code>.
     */
    public final ExerciseTags EXERCISE_TAGS = ExerciseTags.EXERCISE_TAGS;

    /**
     * The table <code>public.exercises</code>.
     */
    public final Exercises EXERCISES = Exercises.EXERCISES;

    /**
     * The table <code>public.tags</code>.
     */
    public final Tags TAGS = Tags.TAGS;

    /**
     * The table <code>public.user_acounts</code>.
     */
    public final UserAcounts USER_ACOUNTS = UserAcounts.USER_ACOUNTS;

    /**
     * The table <code>public.user_advancements</code>.
     */
    public final UserAdvancements USER_ADVANCEMENTS = UserAdvancements.USER_ADVANCEMENTS;

    /**
     * The table <code>public.user_type</code>.
     */
    public final UserType USER_TYPE = UserType.USER_TYPE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.EXERCISE_DIFFICULTIES_ID_SEQ,
            Sequences.TAGS_ID_SEQ,
            Sequences.USER_ADVANCEMENTS_SEQUENCE_NUMBER_SEQ,
            Sequences.USER_TYPE_ID_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ExerciseDifficulties.EXERCISE_DIFFICULTIES,
            ExerciseTags.EXERCISE_TAGS,
            Exercises.EXERCISES,
            Tags.TAGS,
            UserAcounts.USER_ACOUNTS,
            UserAdvancements.USER_ADVANCEMENTS,
            UserType.USER_TYPE
        );
    }
}
