/*
 * This file is generated by jOOQ.
 */
package org.oana.storage;


import org.oana.storage.tables.ExerciseDifficulties;
import org.oana.storage.tables.ExerciseTags;
import org.oana.storage.tables.Exercises;
import org.oana.storage.tables.Tags;
import org.oana.storage.tables.UserAcounts;
import org.oana.storage.tables.UserAdvancements;
import org.oana.storage.tables.UserType;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.exercise_difficulties</code>.
     */
    public static final ExerciseDifficulties EXERCISE_DIFFICULTIES = ExerciseDifficulties.EXERCISE_DIFFICULTIES;

    /**
     * The table <code>public.exercise_tags</code>.
     */
    public static final ExerciseTags EXERCISE_TAGS = ExerciseTags.EXERCISE_TAGS;

    /**
     * The table <code>public.exercises</code>.
     */
    public static final Exercises EXERCISES = Exercises.EXERCISES;

    /**
     * The table <code>public.tags</code>.
     */
    public static final Tags TAGS = Tags.TAGS;

    /**
     * The table <code>public.user_acounts</code>.
     */
    public static final UserAcounts USER_ACOUNTS = UserAcounts.USER_ACOUNTS;

    /**
     * The table <code>public.user_advancements</code>.
     */
    public static final UserAdvancements USER_ADVANCEMENTS = UserAdvancements.USER_ADVANCEMENTS;

    /**
     * The table <code>public.user_type</code>.
     */
    public static final UserType USER_TYPE = UserType.USER_TYPE;
}
